import '../styles/globals.css'
import { Inter } from 'next/font/google'

import AuthContext from '../context/AuthContext'
import ToastContext from '../context/ToasterContext'
import UserContextProvider from '../context/UserContext'
import ReviewsContextProvider from '../context/ReviewsContext'

import Navbar from '../components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PenPal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  process.env.NODE_OPTIONS = '--no-warnings';

  return (
    <AuthContext>
      <UserContextProvider>
        <ReviewsContextProvider>
          <html lang="en" className="h-full">
            <body className={`${inter.className} flex flex-col min-h-screen relative`}>
              <div className="main">
                  <div className="gradient"/>
              </div>
              <main className='app'>
                <Navbar />
                <ToastContext />
                {children}
              </main>
            </body>
          </html>
        </ReviewsContextProvider>
      </UserContextProvider>
    </AuthContext>
  );
}