import './globals.css'
import { Inter } from 'next/font/google'

import AuthContext from './context/AuthContext'
import ToastContext from './context/ToastContext'
import Navbar from './components/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SnailMail',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AuthContext>
          <ToastContext />
          <Navbar />
          <div className='pt-[5rem] px-4'>
            {children}
          </div>
        </AuthContext>
      </body>
    </html>
  )
}
