import './globals.css'
import { Inter } from 'next/font/google'

import AuthContext from './context/AuthContext'
import ToastContext from './context/ToasterContext'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PenPal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AuthContext>
      <html lang="en" className="h-full">
        <body className={`${inter.className} flex flex-col min-h-screen relative`}>
          <nav className='flex justify-between items-center px-4 py-6 border-b fixed top-0 w-full h-16'>
            <Navbar />
          </nav>
          <main className="mt-16 p-4">
            <ToastContext />
            {children}
          </main>
        </body>
      </html>
    </AuthContext>
  );
}